Dhenkel/implement retry wall
DataDog/draino pull request #110
Opened 2022-11-24 14:58 UTC by dhenkel92

This will add a new implementation of a retry wall, which introduces new possibilities, but also respects the current annotations/behaviour.

2022-11-24 15:26 UTC, dhenkel92 commented
I'm not sure where to handle the `drain-retry-failed=restart` annotaion. We could either do it in the retry-wall or in the handler that is using the wall later on.

2022-11-25 10:13 UTC, dbenque requested changes

2022-11-25 10:13 UTC, dbenque commented on internal/kubernetes/drain/retry_wall.go
> +	// NoteDrainFailure will increase the retry-cont on the nde by one
s/nde/node

2022-11-25 10:13 UTC, dbenque commented on internal/kubernetes/drain/retry_wall.go
> +	RegisterRetryStrategies(...RetryStrategy)
I don't understand why this RegisterRetryStrategies func is part the interface.
Shouldn't the set of strategies passed to the constructor of the implementation only. Who is going to call that once the RetryWall is instantiated and why ?

2022-11-25 10:13 UTC, dbenque commented on internal/kubernetes/drain/retry_wall.go
> +	GetDelay(*corev1.Node) (delay time.Duration)
I would have gone one step above in the abstraction and service delivered by this layer.
Placing myself in the user of that interface I would prefer to have an API that set the TimeStampWall on the node.
In other words something like:
`SetNewTimestampRetryWallOnNode(*corev1.Node, now time.Time)` // Of course the now is just to pass current timestamp to ease testing and do potential bck/future activities.
This internally would do the GetDelay, add to now, and increase the retry count. So the NoteDrainFailure is also used internally and don't need to be exposed in the interface.

And next to this in interface:
`GetTimestampRetryWallFromNode(*corev1.Node) time.Time`
`GetDrainRetryAttemptsCount(*corev1.Node) int`

2022-11-25 11:53 UTC, dhenkel92 commented on internal/kubernetes/drain/retry_strategies.go
> +// It will return useDefault=true if none of the annotations was set.
The parameter came up during the implementation where I had a version that was returning `useDefault=true` in case of an error.
I've kept it to try to decouple the `NodeAnnotationStrategy` from the actual default because otherwise, the retry-wall would always use it. This could make a difference if we decide to have diverging defaults for both cases, like `StaticRetry` for `NodeAnnotationStrategy` and `Backoff` as the general default.

2022-11-25 11:53 UTC, dhenkel92 commented on internal/kubernetes/drain/retry_wall.go
> +const RetryWallCountAnnotation = "draino/retry-attempt"
As we have our own draino implementation by now, what do you think about unifying it with the other NLA related labels or make it configurable via arguments?

2022-11-25 11:53 UTC, dhenkel92 commented on internal/kubernetes/drain/retry_wall.go
> +	RegisterRetryStrategies(...RetryStrategy)
Agree :+1: 
I like that we are tanking the time to do proper PR reviews and even think about these small things 🙂

2022-11-25 11:53 UTC, dhenkel92 commented on internal/kubernetes/drain/retry_strategies.go
> +	// GetMaxRetries will return the amount of accepted retries
Right now, we have the idea to use `MaxRetries` as a soft limit to trigger alerting or smth similar. `-1` would deactivate this behaviour, whereas the drain retries would go on.
In this case, and especially in the beginning, we should not deactivate the alerting to make the cases visible.

2022-11-25 11:53 UTC, dhenkel92 commented on internal/kubernetes/drain/retry_wall.go
> +	GetDelay(*corev1.Node) (delay time.Duration)
Makes perfect sense to me

2022-11-25 12:00 UTC, dhenkel92 commented on internal/kubernetes/drain/retry_strategies.go
> +	// GetMaxRetries will return the amount of accepted retries
Renamed it to AlertThreashold to make it clearer.

2022-11-25 12:03 UTC, dbenque commented on internal/kubernetes/drain/retry_strategies.go
> +// It will return useDefault=true if none of the annotations was set.
I don't think "diverging defaults" would be a good, the solution will be hard to read. I would expect to decide at program level for one Default that is passed to the RetryWall, and behind the scene it use that one as default for every cases where we don't find an override.

2022-11-25 12:07 UTC, dbenque commented on internal/kubernetes/drain/retry_wall.go
> +const RetryWallCountAnnotation = "draino/retry-attempt"
I am thinking about if we have to upstream this a some point... I am wondering if we should not use a node condition instead of an annotation.
With a condition we would have more data: first timestamp, last timestamp and the value would go to the message... message that could convey the last failure error message after the count, example: "attempt 4, pod XYZ blocked by its pdb"

2022-11-28 10:46 UTC, dhenkel92 commented on internal/kubernetes/drain/retry_wall.go
> +const RetryWallCountAnnotation = "draino/retry-attempt"
We've decided to move it to a node condition.

2022-11-28 21:35 UTC, dbenque commented on internal/kubernetes/drain/retry_wall.go
> +	// If there was no drain failure yet, it will return a timestamp in the past.
as mentioned in another comment the `time.Time{}` can be returned in case the node never had a failure.
This allow to differentiate the case of past failure vs no failure. There is also the retry count that can help to do that determination.

2022-11-28 21:35 UTC, dbenque commented on internal/kubernetes/drain/retry_wall.go
> +	strategies      map[string]RetryStrategy
I am not clear on what you want to do with this `strategies` map.
I can see the register function that fills that map... but later it is never consumed.
How will the user select the strategy? Based on what you have done, I would say that the user has to mention the name of the strategies on the node... in that case which piece of the code is supposed to read this?
Looks like a part is missing here, or I have not understood something. I would expect something inside function `getStrategyFromNode` and/or `BuildNodeAnnotationRetryStrategy` ...

2022-11-28 21:35 UTC, dbenque commented on internal/kubernetes/drain/retry_wall.go
> +type RetryWall interface {
For future observability layer I would add a function: `IsAboveAlertingThreshold(*core1.Node) bool`

2022-11-28 21:35 UTC, dbenque commented on internal/kubernetes/drain/retry_wall.go
> +	node.Status.Conditions[pos].Message = fmt.Sprintf("%d%s%s", retryCount, retryConditionMsgSeparator, reason)
Can we write 2 methods `serializeCondition` and `unserializeCondition` that are only in charge of the string formation and decoding.
This way we are sure that they evolve in a symetric way in the future, and they can be reused elsewhere if needed.
Also that would be a clear scope in case we need to refine the format and handle migration on the format change.

2022-11-29 09:14 UTC, dhenkel92 commented on internal/kubernetes/drain/retry_wall.go
> +	strategies      map[string]RetryStrategy
Ah you are right. There was an open TODO left in `getStrategyFromNode`. I've implemented the logic and now it's possible to select a strategy on node level.

2022-11-29 15:37 UTC, dbenque approved these changes

2022-11-29 15:37 UTC, dbenque commented on internal/kubernetes/drain/retry_wall.go
> +var TimeDefault = time.Time{}
Let's name it `TimeZero`

2022-11-29 20:36 UTC, dbenque approved these changes

2022-11-30 06:44 UTC, merged