implement drain buffer to store last drain of nodegroup
DataDog/draino pull request #123
Opened 2022-12-22 14:50 UTC by dhenkel92

2022-12-23 10:09 UTC, dbenque requested changes
Asking for persistor to be injected in the drainbuffer (no internal build)
We need to discuss the usage of context to pass parameters

2022-12-23 10:09 UTC, dbenque commented on internal/drain_runner/runner.go
> +	entry := ctx.Value(groups.CTXGroupKey)
I am not really sure we show use context to convey parameters.
Why the key and not the node ? ...
I think we should pass the `info *groups.RunnerInfo` as parameter to the functions.
One of my intention was also to convey that struct to collect information that we can use later in the CLI.

2022-12-23 14:01 UTC, dhenkel92 commented on internal/drain_buffer/drain_buffer.go
> +	// TODO compare drain buffer and update if not the same
The Idea was if the drain-buffer changed over time, we can might want to update the cached drain-buffer as well.

2022-12-23 14:02 UTC, dhenkel92 commented on internal/drain_buffer/drain_buffer.go
> +	buffer.cache[string(key)] = drainCacheEntry{
That's a very good idea

2022-12-23 14:33 UTC, dhenkel92 commented on internal/drain_buffer/drain_buffer.go
> +func NewDrainBuffer(ctx context.Context, client client.Client, clock clock.Clock, logger *logr.Logger, name, namespace string) (DrainBuffer, error) {
Generally, I would agree, but in this case we would have to export the internal drainCache & drainCacheEntry structs, which would leak some implementation details.
So, I'm not sure what's the best approach in this case.

2022-12-23 14:49 UTC, dhenkel92 commented on internal/drain_runner/runner.go
> +	entry := ctx.Value(groups.CTXGroupKey)
I've refactored it to use the runner info instead of context value.

2022-12-23 14:49 UTC, dhenkel92 commented on internal/drain_buffer/drain_buffer.go
> +	NoteSuccessfulDrain(groups.GroupKey, time.Duration)
I think both are fine. I can change it if you really want.

2022-12-27 13:37 UTC, dbenque requested changes

2022-12-27 13:37 UTC, dbenque commented on internal/drain_buffer/drain_buffer.go
> +	NoteSuccessfulDrain(groups.GroupKey, time.Duration)
Prefer "store" or "save" that better carry the idea of persistence IMO.

2022-12-27 13:37 UTC, dbenque commented on internal/drain_buffer/drain_buffer.go
> +func NewDrainBuffer(ctx context.Context, client client.Client, clock clock.Clock, logger *logr.Logger, name, namespace string) (DrainBuffer, error) {
This is due to your choice to template the Persistor with the exact type.
The Persistor does not need to know the exact type. There is no real need for that, the persistor should take a []byte, because this is the only thing that we need to persist an object in either a ConfigMap or a document store or whatever.
This would make the Persistor more generic and injectable.

2022-12-27 13:37 UTC, dbenque commented on internal/drain_buffer/drain_buffer.go
> +	// TODO compare drain buffer and update if not the same
ok I see. If the new drainBuffer is bigger and we do not update, we risk the fact that the entry is cleanup. If we want the system to respect the current config, then we should update.
On the other side if we do this we are let with another problem: How do we ensure that all entries are updated in time (before cleanup) in case a new drain-buffer is provided.

I think that the contract is more clear if we state that drain-buffer value is ALWAYS the one corresponding to the moment of the drain. In other words NextDrain function should not take anydrainBuffer value as parameter and always used the cached value,

2022-12-27 14:21 UTC, dhenkel92 commented on internal/drain_buffer/drain_buffer.go
> +func NewDrainBuffer(ctx context.Context, client client.Client, clock clock.Clock, logger *logr.Logger, name, namespace string) (DrainBuffer, error) {
I don't agree with `more generic and injectable.`. The current implementation is quite generic already and abstracts even more of the implementation details. In this case, the persistor can decide about how to serialize and further escape the data before writing it somewhere. Furthermore, a generic persistor mock is equally easy to implement and can be used in tests without  calling the `NewDrainBuffer` method.

Using []byte instead of the generic would just move the flexibility problem to somewhere else.

2022-12-27 14:21 UTC, dhenkel92 commented on internal/drain_buffer/drain_buffer.go
> +	// TODO compare drain buffer and update if not the same
Okay, your explanation makes a lot of sense and I like sticking to the exact contract. Then we & the user will always know what to expect and we have less side effects. I'll update the function 🙂

2022-12-27 14:47 UTC, dbenque commented on internal/drain_buffer/drain_buffer.go
> +func NewDrainBuffer(ctx context.Context, client client.Client, clock clock.Clock, logger *logr.Logger, name, namespace string) (DrainBuffer, error) {
No agreement here: usage of generics does not directly mean more generic code. We have a clear example with this implementation that results in entangled code with an impossible separation of layers (separation between persistence and struct). The decision of how the persistence should be done must live outside the struct itself. Using other words, your implementation choice makes it impossible to apply dependency injection. 

I would not block the PR because of this, we need to move forward.

2022-12-27 14:48 UTC, dbenque approved these changes
Approving because I want us to move forward, but I would clearly have done this differently:
https://github.com/DataDog/draino/pull/123#discussion_r1057722147

2022-12-28 09:16 UTC, dbenque approved these changes

2022-12-28 09:39 UTC, merged