reset retry wall if node has drain failed retry annotation
DataDog/draino pull request #126
Opened 2022-12-27 06:54 UTC by dhenkel92

2022-12-27 08:21 UTC, dbenque requested changes

2022-12-27 08:21 UTC, dbenque commented on internal/candidate_runner/runner.go
> +				return err
Save the error(s), continue with other nodes and return the aggregated error at the end.

2022-12-27 15:17 UTC, dbenque approved these changes

2022-12-27 15:37 UTC, dhenkel92 commented
I've rebased the branch to resolve merge-conflics

2022-12-28 09:29 UTC, dbenque commented on internal/candidate_runner/runner.go
> +		if err := runner.handleRetryFlagOnNodes(ctx, nodes); err != nil {
What about running this in a dedicated go routine ?
I see couple of advantages:
- do not delay the processing of candidates. Better perf if the process can get resources.
- in case of error with this part, the rest of the processing is not affected

2022-12-28 09:29 UTC, dbenque approved these changes

2022-12-28 10:30 UTC, dhenkel92 commented on internal/candidate_runner/runner.go
> +		if err := runner.handleRetryFlagOnNodes(ctx, nodes); err != nil {
As discussed: we are going to create a POC of a separate routine in a different PR.
Nevertheless, I've updated the error handling in this one.

2022-12-28 10:34 UTC, dbenque approved these changes

2022-12-28 10:37 UTC, merged