remove drain candidate taint if user manually opts out a node
DataDog/draino pull request #128
Opened 2022-12-27 07:28 UTC by dhenkel92

2022-12-27 08:29 UTC, dbenque commented on internal/drain_runner/runner.go
> +	if val, exist := candidate.Annotations[kubernetes.NodeNLAEnableLabelKey]; exist && val == "false" {
We have to be more general than that and use the nodefilterFunc, just like in candidate_runner filters.

2022-12-27 08:30 UTC, dbenque commented on internal/drain_runner/runner.go
> +	if val, exist := candidate.Annotations[kubernetes.NodeNLAEnableLabelKey]; exist && val == "false" {
Maybe we can postpone that PR and come back to it when the "filter" PR will be merged.

2022-12-27 08:30 UTC, dbenque requested changes
Need a more general filter. Postpone after "Filter" PR

2022-12-27 10:41 UTC, dhenkel92 commented on internal/drain_runner/runner.go
> +	if val, exist := candidate.Annotations[kubernetes.NodeNLAEnableLabelKey]; exist && val == "false" {
Okay I see, so we don't want to have a check if someone opted out the node manually, but more like a check if the requirements still apply before executing the drain.

2022-12-28 07:10 UTC, dhenkel92 commented on cmd/draino/draino.go
> +		drain_runner.WithFilter(filter),
I'm not sure if we should use the whole set of filters or just a special part, like pod annotation and node labels.

2022-12-28 09:52 UTC, dbenque commented on cmd/draino/draino.go
> +		drain_runner.WithFilter(filter),
We should differentiate them, I prefer to avoid any side effect from other filters. Our purpose here is really scope.
I propose this:
https://github.com/DataDog/draino/pull/130

2022-12-28 09:57 UTC, dbenque approved these changes

2022-12-28 10:32 UTC, dbenque approved these changes

2022-12-28 10:38 UTC, merged