add drain buffer filter
DataDog/draino pull request #132
Opened 2022-12-28 11:44 UTC by dhenkel92

2022-12-28 13:45 UTC, dhenkel92 commented on cmd/draino/options.go
> +		o.drainBufferConfigMapName = fmt.Sprintf("draino-%s-drain-buffer", o.configName)
I'm not sure about this part. The idea was to make misconfiguration harder in case we run multiple instances of draino.

2022-12-28 15:18 UTC, dhenkel92 commented on internal/drain_buffer/drain_buffer.go
> -	cacheBytes, exist, err := persistor.Load()
There was a problem with the config map persistor. When we try to load the data at this point, the `load` command will fail because the the kubernetes client cache is not initialised yet 😞 
```
the cache is not started, can not read objects
```

I don't like the implementation, but I haven't had a better idea.

2022-12-29 09:06 UTC, dbenque commented on cmd/draino/options.go
> +		o.drainBufferConfigMapName = fmt.Sprintf("draino-%s-drain-buffer", o.configName)
LGTM

2022-12-29 09:19 UTC, dbenque commented on internal/drain_runner/runner.go
> +		return err
This is not great... we are going to let the node in `draining` while in fact it is drained and we just failed to persist that success.

I propose that you add a method `IsReady` to the `DrainBuffer` interface. We would call this method before starting any drain activity. This way the node will stay in `drain_candidate` state which is acceptable. We would log a line "waiting for drainBuffer to be ready".

2022-12-29 09:20 UTC, dbenque requested changes
I propose to not start any drain if the DrainBuffer is not initialised. We just need to expose one more func in the interface for that.

2022-12-29 11:20 UTC, dbenque approved these changes
We probably want to add a timeout to RunTillSuccess

2022-12-29 12:28 UTC, dbenque approved these changes

2022-12-29 12:50 UTC, merged