add drain candidate runner loop duration to metrics
DataDog/draino pull request #140
Opened 2023-01-02 13:13 UTC by dhenkel92

This PR is adding new metrics to monitor drain candidate / drain runner main loops.

2023-01-02 13:45 UTC, dbenque requested changes

2023-01-02 13:45 UTC, dbenque commented on internal/drain_runner/runner.go
> +		before := runner.clock.Now()
s/before/start

2023-01-02 13:45 UTC, dbenque commented on internal/observability/observability.go
> +		candidateDataInfo.Import(raw)
We are in the process, the value does not come from any serialisation, so you can do a type cast instead of going through serialisation again.

2023-01-02 13:58 UTC, dhenkel92 commented on internal/observability/observability.go
> +		candidateDataInfo.Import(raw)
Very good point 🙇

2023-01-02 15:47 UTC, dbenque approved these changes

2023-01-03 11:03 UTC, dbenque approved these changes

2023-01-03 11:03 UTC, merged