skip pre-activities defined on controller level
DataDog/draino pull request #193
Opened 2023-01-31 13:02 UTC by dhenkel92

2023-01-31 13:28 UTC, dhenkel92 commented
https://datadoghq.atlassian.net/wiki/pages/diffpagesbyversion.action?pageId=2791706268&selectedPageVersions=4&selectedPageVersions=5

2023-02-02 13:02 UTC, dbenque requested changes

2023-02-02 13:02 UTC, dbenque commented on internal/drain_runner/pre_processor/pre_activities.go
> +			continue
We are missing user feedback on that path, since we have an eventRecorder in `PreActivitiesPreProcessor` would be good to send a warning to the user

2023-02-02 14:08 UTC, dhenkel92 commented on internal/drain_runner/pre_processor/pre_activities.go
> +			continue
Even tho I don't like reacting on not supported configuration, it might be a good indicator for misconfiguration on their side.
But this means we have to be consistent, so i'll set the stopIfFoundOnPod flag to false again.

2023-02-02 15:54 UTC, dbenque approved these changes

2023-02-02 15:57 UTC, merged