inscope-observability
DataDog/draino pull request #21
Opened 2021-04-19 14:59 UTC by dbenque

The controller annotate the nodes that are in scope with the name of the `draino` configuration (annotation key: `node-lifecycle.datadoghq.com/draino-configuration`)

It also generates a metric (gauge) the reflect how many nodes are in scope or not for each condition. A virtual condition `any` is created to gain visibility on nodes that are not marked by any condition.

Example:
```
draino_in_scope_nodes_total{conditions="all",in_scope="false",nodegroup_name="perf-1",nodegroup_namespace="proxy-exp",team=""} 9
draino_in_scope_nodes_total{conditions="all",in_scope="false",nodegroup_name="sre-default",nodegroup_namespace="sre",team="sre"} 1
draino_in_scope_nodes_total{conditions="all",in_scope="false",nodegroup_name="test-dre",nodegroup_namespace="datadog",team=""} 3
draino_in_scope_nodes_total{conditions="all",in_scope="true",nodegroup_name="cluster-controllers",nodegroup_namespace="cluster-controllers",team=""} 5
```

2021-04-19 19:38 UTC, adrienjt requested changes
Nicely done! See line-specific comments for details.

General note: I would have liked to see this PR split into at least two commits to help me navigate it (I figured it out eventually, so no big deal): a refactor that moves code from eventhandler(_test).go to conditions(_test).go; another with the actual feature.

2021-04-19 19:38 UTC, adrienjt commented on internal/kubernetes/observability.go
> +// Note: with opencensus unregistering/registering the view would clean-up the old series. The problem is that a metrics has to be registered to be recorded.
You could record 0 for TagContexts that don't exist anymore. (You'd have to keep the previous iteration's TagContexts in memory to do that.)

2021-04-19 19:38 UTC, adrienjt commented on internal/kubernetes/observability.go
> +				freshNode, err := s.kclient.CoreV1().Nodes().Get(node.Name, metav1.GetOptions{})
This Get call is unnecessary in most cases. You could Get only if the first Update fail (if the cached Node is indeed outdated). Better, you could Patch.

2021-04-19 19:38 UTC, adrienjt commented on internal/kubernetes/observability_test.go
> +				return strings.Contains(v, "other") && strings.Contains(v, "draino1")
This test does not cover the contract that configuration names are comma-separated.

2021-04-19 19:38 UTC, adrienjt commented on internal/kubernetes/observability_test.go
> +	tests := []struct {
Should you add test cases with pod filters?

2021-04-20 07:45 UTC, dbenque commented on internal/kubernetes/observability.go
> +// Note: with opencensus unregistering/registering the view would clean-up the old series. The problem is that a metrics has to be registered to be recorded.
Well I am not sure that is a good solution, I usually prefer to GC unwanted series:
- the gauge will show 0 for series that does not exist anymore
-- absence of series (no existence) and  series with value 0 could have different meaning (in that case not important)
-- the data pollution associated with useless, unwanted series is really something I want to reduce (mem footprint, datastorage on product side,...)
- I will have to keep track of all previous series from one run to another which is possible but if I can avoid this it is better.
- A controller restart would cleanup unwanted series: this way we have same behavior on long run.

2021-04-20 07:53 UTC, dbenque commented on internal/kubernetes/observability.go
> +				freshNode, err := s.kclient.CoreV1().Nodes().Get(node.Name, metav1.GetOptions{})
True for patch in general, except that pathing annotations (and more generally map or slice) is dangerous and opened to concurrency issue. You cannot patch only one key in the map as far as I know (I always see code with full map, if you have code for only one key I am interested) and as a consequence a concurrent patch with another annotation change would discard one of the changes.

For the Get it is useless for the 15 first nodes: since nodes are patched every 30s (heartbeat) and we pace the updates at 2 per second, there is a chance that the first 15 first nodes are ok in the cache, but for all the rest (usually thousands), the update is going to fail.

2021-04-20 07:54 UTC, dbenque commented on internal/kubernetes/observability_test.go
> +				return strings.Contains(v, "other") && strings.Contains(v, "draino1")
true, I am going to make it more precise.

2021-04-20 08:07 UTC, dbenque commented on internal/kubernetes/observability_test.go
> +	tests := []struct {
indeed, that would give a better coverage for the underlying function `IsInScope`

2021-04-20 08:21 UTC, dbenque commented on internal/kubernetes/observability_test.go
> +	tests := []struct {
done

2021-04-20 08:21 UTC, dbenque commented on internal/kubernetes/observability_test.go
> +				return strings.Contains(v, "other") && strings.Contains(v, "draino1")
done

2021-04-20 14:20 UTC, adrienjt commented on internal/kubernetes/observability.go
> +				freshNode, err := s.kclient.CoreV1().Nodes().Get(node.Name, metav1.GetOptions{})
Patching maps is not dangerous. That's what `kubectl annotate` does. Try it with `--v=8` and you'll see. To remove a key, the payload looks like this:

```
Request Body: {"metadata":{"annotations":{"foo":null}}}
```

By the way, patching slices is tricky, but sometimes possible with strategic mode.

2021-04-21 12:29 UTC, dbenque commented on internal/kubernetes/observability.go
> +				freshNode, err := s.kclient.CoreV1().Nodes().Get(node.Name, metav1.GetOptions{})
Finally manage to make it. I failed in the past cause I was always using JSON patch instead of merge.

2021-04-21 14:57 UTC, adrienjt commented on internal/kubernetes/observability.go
> +		}
Unnecessary check. If a map is nil, looking up a key returns the zero-value, here the empty string.

2021-04-21 14:57 UTC, adrienjt commented on internal/kubernetes/observability.go
> +		}
Probably unnecessary too. Actually confusing here, because `userOptOutPodFilter` abstracts the fact that we're checking annotations.

2021-04-21 14:57 UTC, adrienjt commented on internal/kubernetes/observability.go
> +		return PatchNodeAnnotationKey(s.kclient, nodeName, ConfigurationAnnotationKey, "")
if `len(newConfig) == 0`, calling PatchNodeAnnotationKey with "" is like calling it with newConfig, so the conditional is unnecessary.

2021-04-21 15:13 UTC, dbenque commented on internal/kubernetes/observability.go
> +		}
yes not sure why I have these tests against annotation nil map... maybe here some previous test I was doing. Clearly not needed anymore.
Thanks for spotting this.

2021-04-21 15:17 UTC, dbenque commented on internal/kubernetes/observability.go
> +		return PatchNodeAnnotationKey(s.kclient, nodeName, ConfigurationAnnotationKey, "")
100%, this conditional was making sense when I was removing the annotation instead of setting it with an empty value.
I am removing it now.

2021-04-21 15:22 UTC, adrienjt approved these changes

2021-04-21 15:31 UTC, merged