tooling to remove drainCandidate taint
DataDog/draino pull request #231
Opened 2023-03-17 16:19 UTC by dbenque

2023-03-20 10:37 UTC, dhenkel92 requested changes

2023-03-20 10:37 UTC, dhenkel92 commented on tools/taints.go
> +		Args:       cobra.MaximumNArgs(1),
I think we could use minimum args here to make sure that it will be called with an argument.
```suggestion
		Args:       cobra.MinimumNArgs(1),
```

2023-03-20 11:16 UTC, dbenque commented on tools/main.go
> +		fmt.Errorf("error while creating manager: %v\n", err)
done

2023-03-20 11:24 UTC, dbenque commented on tools/main.go
> +	mgr, logger, _, err := controllerruntime.NewManager(cfg)
The flags are all optional, running with default values is fine as soon as the current context is set. If not the program will complain that it is missing the kube context. All this comes with the compute-go library and allow you to tune the behaviour if you want... In our case we don't have the need.

It is the same "complexity" than for any of our program that is based on `compute-go` and build kube client (or manager). In other words the "complexity" is killed by homogeneity: we do the same thing everywhere! Most the time the default options are fine, but any tuning is done the same way in every program thanks to this. This is why we have all the charts that look the same when it comes to options.

For the controller-manager it is not strickly needed here, I could have used a simple client. But since I am opening the tool to host more command I don't want to limit the capabilities for future extensions that would require the informers. Also I am using primitives of the core draino packages like `k8sclient.RemoveNLATaint` that take a Client of the controller-runtime library. The manager nicely builds it. All in all using the manager appeared to me as a good compromise: know pattern, reused code, open for future extension.

2023-03-20 11:27 UTC, dbenque commented on tools/main.go
> +	}
Zap is backing our logr.Logger ... I have not check if it is still needed but I remember that the Sync was/is here to ensure that all the logs line are flushed before the program exit. We have the same in the main of `draino`.

2023-03-20 11:34 UTC, dbenque commented on tools/taints.go
> +		Args:       cobra.MaximumNArgs(1),
done

2023-03-20 11:36 UTC, dbenque commented on tools/taints.go
> +		Args:       cobra.MaximumNArgs(1),
done... I am always shared with these options, because we never know of subcommands are going to evolve. I am thinking that if we could set no constraint it would be better in fact.

2023-03-20 11:39 UTC, dbenque commented on tools/taints.go
> +	nodeListerFilter := BuildNodeListerFilter(mgr.GetClient(), taintCmdFlags.nodeName, taintCmdFlags.nodegroupName, taintCmdFlags.nodegroupNamespace)
completely possible, here I am ensuring that the exact same list is passed to both command list/delete. This way less surprise, I know that what is listed should be the same that what is deleted. Of course the commands are not run at the same time, so the data can be different but at least the method is the same. That was the idea.

2023-03-20 11:43 UTC, dbenque commented on tools/main.go
> +	time.Sleep(time.Second)
Cache on which resource ? at this point there is no informer, and we don't yet know which resource is going to be consumed, which command is going to be played.
If a command starts an informer, I agree we will have to wait for the associated cache, in the command.

In our command we are using `list`. AFAIR this is a blocking call, and the cache is filled up on the fly with that first list.

2023-03-20 11:47 UTC, dbenque commented on tools/taints.go
> +			output, err := FormatNodesOutput(nodes)
So a different output for List and Delete, where Delete is the same than list plus 2 columns ?

2023-03-20 11:48 UTC, dbenque commented on tools/taints.go
> +	}
done

2023-03-20 12:10 UTC, dbenque commented on tools/taints.go
> +	if nodeName != "" {
done, change the function as lister instead of functor also

2023-03-20 12:10 UTC, dbenque commented on tools/taints.go
> +	nodeListerFilter := BuildNodeListerFilter(mgr.GetClient(), taintCmdFlags.nodeName, taintCmdFlags.nodegroupName, taintCmdFlags.nodegroupNamespace)
Changing it and calling the listFunc with all the same parameters instead.

2023-03-20 12:11 UTC, dbenque commented on tools/taints.go
> +		Args:       cobra.MaximumNArgs(1),
done

2023-03-20 13:47 UTC, dhenkel92 commented on tools/taints.go
> +		Args:       cobra.MaximumNArgs(1),
Tbh, it doesn't really matter. On the one hand, I don't think we will not have any problems without this config, and on the other hand, If we want to extend the tool, we can also change this number.

2023-03-20 13:47 UTC, dhenkel92 commented on tools/taints.go
> +					fmt.Printf("%v: %v\n", node.Name, err)
This should also be in the result column.

2023-03-20 13:47 UTC, dhenkel92 commented on tools/taints.go
> +				fmt.Printf("%v: done\n", node.Name)
Is this useful if every node will get it's own entry in the table?

2023-03-20 16:19 UTC, dbenque commented on tools/main.go
> +package main
because anything under `./cmd/` will go to the image and I would like to avoid that.
https://github.com/DataDog/compute-delivery/blob/74295c2ed42b5f8d4fbfce71deec0ee04b57688a/README.md#what-it-does

2023-03-20 16:32 UTC, dbenque commented on tools/main.go
> +	time.Sleep(time.Second)
To ensure that the manager could start few basic elements in the goroutine:
https://github.com/kubernetes-sigs/controller-runtime/blob/release-0.14/pkg/manager/internal.go#L446

I didn't want (nor have time) to make assumptions on how the client is build on New or on Start, this might even change along versions of CR, so I have been lazy.

2023-03-20 16:36 UTC, dbenque commented on tools/taints.go
> +	if nodeName != "" {
done

2023-03-20 16:39 UTC, dbenque commented on tools/taints.go
> +					fmt.Printf("%v: %v\n", node.Name, err)
of course, went too fast

2023-03-20 16:40 UTC, dbenque commented on tools/taints.go
> +				fmt.Printf("%v: done\n", node.Name)
same I forgot that one, I went too fast

2023-03-20 16:59 UTC, dbenque commented on tools/main.go
> +	mgr, logger, _, err := controllerruntime.NewManager(cfg)
removing the hammer (manager and logger removed)

Doing test I found a problem with the client configuration. Some flag are not correctly taken into account, but the problem is more in `compute-go` library. I will switch there to fix.

2023-03-21 07:31 UTC, dhenkel92 commented on tools/main.go
> +package main
> ... will build a Go binary and Docker image for every directory ...

Everything under `./cmd/` will get it's own binary / Docker image.

2023-03-21 07:34 UTC, dhenkel92 commented on tools/main.go
> +	time.Sleep(time.Second)
😄  okay

2023-03-21 07:41 UTC, dhenkel92 submitted a review, later dismissed

2023-03-21 10:02 UTC, dhenkel92 approved these changes

2023-03-21 10:30 UTC, merged