Eviction++ dry-run
DataDog/draino pull request #256
Opened 2023-06-14 18:06 UTC by rrangith

This adds support for dry-run eviction requests to custom eviction urls. Previously we would assume they pass simulation and return early. Now if a pod or its controller has the annotation `draino/eviction-api-dry-run-supported`, it will send a request to the same custom eviction url but with an extra parameter in the json payload like how we do it for kubernetes evictions https://github.com/DataDog/draino/blob/133685a72502fd717b6de1d7c1ac7ca814b78755/internal/kubernetes/drain/simulator.go#L221-L229. If the pod is not opted in, then we will continue to pass simulation early.

If the pod is opted-in, it will not perform pdb checks, this is because the eviction api url should be doing all necessary checks, and might not care about pdbs. However, we will check the rate limiter.

TODO: write tests

2023-06-21 08:46 UTC, dhenkel92 requested changes
(I saw the PR by chance and hope it was not too early for a review)

Great job! I'm looking forward to teams implementing the dry-run 😍 
This will reduce the number of errors once again.

Why did we decide against adding it to DBM in the end?

2023-06-21 08:46 UTC, dhenkel92 commented on internal/kubernetes/drainer.go
> +	EvictionAPIDryRunSupportedAnnotationKey = "draino/eviction-api-dry-run-supported"
/nit 
What do you think about migrating the label away from `draino/...`? I remember that we thought about replacing the label with something new at some point. Maybe:
```
node-lifecycle.datadoghq.com/eviction-api-url-with-dry-run:
```
Even if my proposal name is not 100% convincing, it might be a good time. The idea would be that the teams implement the dry-run and then replace the label.

@dbenque What do you think? Do we even want to unify the labels?

2023-06-21 08:46 UTC, dhenkel92 commented on internal/kubernetes/drainer.go
> +func CallOperatorAPI(ctx context.Context, logger logr.Logger, url string, pod *core.Pod, conditions []string, dryRun bool, maxRetryOn500 int) (*http.Response, error) {
As this is a dedicated function now, could we add tests here as well?

2023-06-21 08:46 UTC, dhenkel92 commented on internal/kubernetes/drain/simulator.go
> +	runtimeObjectStore kubernetes.RuntimeObjectStore
We should get rid of the `RuntimeObjectStore` at some point, but unfortunately, there is no other way right now 😅

2023-06-21 08:46 UTC, dhenkel92 commented on internal/kubernetes/drain/simulator.go
> +func (sim *drainSimulatorImpl) operatorAPIDryRunNotOptedIn(pod *corev1.Pod) bool {
What do you think about `operatorAPIDryRunEnabled` to make it more readable?

2023-06-21 08:46 UTC, dhenkel92 commented on internal/kubernetes/drain/simulator.go
> +		}
/nit 
```suggestion
		_, ok := kubernetes.GetAnnotationFromPodOrController(kubernetes.EvictionAPIDryRunSupportedAnnotationKey, pod, sim.runtimeObjectStore);
		return !ok
```

2023-06-21 08:46 UTC, dhenkel92 commented on internal/kubernetes/drain/simulator.go
> +func (sim *drainSimulatorImpl) SimulatePodDrain(ctx context.Context, pod *corev1.Pod, node *corev1.Node) (bool, string, error) {
What do you think about adding a metric to the whole process to get more insights into how many simulations we are running and what's their result?

2023-06-21 08:46 UTC, dhenkel92 commented on internal/kubernetes/drain/simulator.go
>  		if apierrors.IsForbidden(err) { // This is the admission that is rejecting the drain. The error carry the reason for the rejection
Did you check if there are different expected errors that we could receive from eviction++?

2023-06-21 08:46 UTC, dhenkel92 commented on internal/kubernetes/drain/simulator.go
> +		}
/nit
Let's extract this part into it's own function to keep readability.

2023-06-21 15:09 UTC, rrangith commented
> Why did we decide against adding it to DBM in the end?

We saw that most teams use eviction++ in a more complicated way where operations need to be done during real eviction, so they would not benefit from the "disruption probe" aspect of this where cluster autoscaler would be able to safely evict. We decided that we should keep something like a "disruption probe" vs "eviction++ dry run" separate, so in the future if we do decide to add support for a "disruption probe", teams that don't have a complex eviction++ api could make the switch and be eligible for autoscaler evictions

2023-06-21 19:11 UTC, rrangith commented on internal/kubernetes/drain/simulator.go
> +func (sim *drainSimulatorImpl) SimulatePodDrain(ctx context.Context, pod *corev1.Pod, node *corev1.Node) (bool, string, error) {
Yea i saw the todo comments about this for both pod and node
https://github.com/DataDog/draino/blob/ffa73d137134b966978f67ad56c1698afcf75583/internal/kubernetes/drain/simulator.go#L126
https://github.com/DataDog/draino/blob/ffa73d137134b966978f67ad56c1698afcf75583/internal/kubernetes/drain/simulator.go#L136

I think it is out of scope for this pr, so will add it in a followup

2023-06-21 19:17 UTC, rrangith commented on internal/kubernetes/drain/simulator.go
>  		if apierrors.IsForbidden(err) { // This is the admission that is rejecting the drain. The error carry the reason for the rejection
not that I can think of, this is where we handle the response https://github.com/DataDog/draino/blob/ffa73d137134b966978f67ad56c1698afcf75583/internal/kubernetes/drainer.go#L817-L838

2023-06-22 06:54 UTC, dhenkel92 commented on internal/kubernetes/drainer.go
> +	EvictionAPIDryRunSupportedAnnotationKey = "draino/eviction-api-dry-run-supported"
I see what you mean and somewhat agree.
I've added the `with-dry-run` prefix so the teams know why they must replace the label. Furthermore, we assume that dry-run is enabled, but it needs to be visible in the name, which could lead to weird copy-paste issues.

2023-06-22 07:01 UTC, dhenkel92 approved these changes

2023-06-22 14:23 UTC, rrangith commented on internal/kubernetes/drainer.go
> +	EvictionAPIDryRunSupportedAnnotationKey = "draino/eviction-api-dry-run-supported"
makes sense, also curious if @dbenque has thoughts

2023-06-26 15:12 UTC, dbenque commented on internal/kubernetes/drain/simulator.go
> +	SimulatePodDrain(context.Context, *corev1.Pod, *corev1.Node) (canEvict bool, reason string, err error)
Why adding the node to that API? you have the pod and the implementation has a client that can do a get node in O(1) because it is plugged on the informer cache.

2023-06-26 15:12 UTC, dbenque commented on internal/kubernetes/drain/simulator.go
> +		// Too many requests means either we are rate limited (what's expected in some cases) or that the eviction was rejected by the apiserver.
In that case rateLimit is more than improbable... I mean the 429 is part of the contract of the API to say: retry later, but that does not imply rateLimit.

2023-06-27 13:19 UTC, rrangith commented on internal/kubernetes/drain/simulator.go
> +		// Too many requests means either we are rate limited (what's expected in some cases) or that the eviction was rejected by the apiserver.
this was existing code that I just moved over. do you think we should change the comment?

2023-07-03 07:29 UTC, dbenque requested changes

2023-07-03 07:29 UTC, dbenque commented on internal/kubernetes/drain/simulator.go
> +		return false, "node not fouund", err
Maybe we should catch is not found and return a OK in that case?
I would not like the drain of the node to be blocked because a pod is already gone

2023-07-05 14:21 UTC, rrangith commented on internal/kubernetes/drain/simulator.go
> +		return false, "node not fouund", err
hmm this happening would be a weird case, I think it is safe to keep it as is, and simulation can be retried

2023-07-05 14:36 UTC, merged