[COMPUTE-971] [control] automatic exponential backoff on drain retry
DataDog/draino pull request #36
Opened 2021-07-26 19:59 UTC by willquan7

## Description
When too many nodes in the cluster are NotReady, then NLA should stop acting on the cluster.

## Implementation
- New flag *max-drain-attempts-before-fail* enables feature. May be an integer number of retries defaulting to 8.
- New check in EventHandler.HandleNode to fail when retry is exceeded with "Drain Failed: MaxDrainAttempts reached".
- Modifed SchedulesGroup.addSchedule to add backoff-delay on new retry schedules
- Modified APICordonDrainer.MarkDrain to encode retry count in the msgSuffix of the condition, and set annotation 'draino/drain-retry=failed' when/if retry count is exceeded.
- Added Makefile for new feature params
- Added testcases for MarkDrain

*NOTE on backoff delay* 
The delay is calculated in hours but is dependent on the fail attempts so far.
```
delay = 2 * failedCount * Hours 
# with max=8 we would get the sequence
# 1  2  3  4  5  6  7  8
# 1  5 11 19 29 47 55 71
# where the 8th and final retry occurs 71hrs after the initial drain failure (or ~3days of failed retries).
```

Technically this is a geometrical backoff.

## Other Considerations
- metrics: the counter for drain-failure is incremented but there is no counter for final-drain-failure (implying retries happened)
- the node remains cordoned after the drain fails. This is existing behavior. Is it safe to un-cordon?

2021-07-27 12:28 UTC, dbenque requested changes

2021-07-27 12:28 UTC, dbenque commented on internal/kubernetes/drainSchedule.go
> +			return d.drainer.MarkDrain(node, when, time.Time{}, false, 0)
We should pass the real failCount to the MarkDrain here.

2021-07-27 12:28 UTC, dbenque commented on internal/kubernetes/drainSchedule.go
> +				return d.drainer.MarkDrain(node, when, sched.finish, false, 0)
We should pass the real failCount to the MarkDrain here.

2021-07-27 12:28 UTC, dbenque commented on internal/kubernetes/drainer.go
> +func NewAPICordonDrainer(c kubernetes.Interface, eventRecorder record.EventRecorder, maxDrainAttemptsBeforeFail int, ao ...APICordonDrainerOption) *APICordonDrainer {
As mentioned earlier, I would try to favor the APICordonDrainerOption and not adding extra param to the constructor

2021-07-27 12:28 UTC, dbenque commented on internal/kubernetes/drainer.go
>  			msgSuffix = fmt.Sprintf(" | %s: %s", CompletedStr, finish.Format(time.RFC3339))
I am thinking that we should always serialize the `failCount` whatever the context. Of course that means that we should revisit the format a bit. What do you think about:
```
msgPrefix=fmt.Sprintf("[%d] ",failCount)
freshNode.Status.Conditions[i].Message = msgPrefix+"Drain activity scheduled " + when.Format(time.RFC3339) + msgSuffix
```

This way whenever we have a condition (sheduled|completed|failed) we have the information of the number of attempts.

Of course the IsMarkedForDrain function that is doing the decoding will have to be adapted to that format. (+ taking into account existing format without prefix for the migration)

2021-07-27 12:28 UTC, dbenque commented on internal/kubernetes/eventhandler.go
> +		if elapseSinceCompleted >= h.durationWithCompletedStatusBeforeReplacement {
what did motivate that change ?

2021-07-27 12:28 UTC, dbenque commented on internal/kubernetes/eventhandler.go
> +				logger.Warn("Drain Failed: MaxDrainAttempts reached")
In that case we need to do more:
- change the draino retry annotation value to `draino/retry=failed`
- uncordon the node to release the slot used by this node... the fact that we have marked it with the annotation will allow us to:
-- not re-cordon that node, and let it for user to handle
-- once the user has taken the actions to fix the problem, it can just remove the annotation and this way the node is re-injected in the normal flow and become candidate again.

2021-07-27 14:56 UTC, willquan7 commented on cmd/draino/draino.go
> +		*maxDrainAttemptsBeforeFail,
ok

2021-07-30 15:51 UTC, dbenque requested changes
Some minor comments.

2021-07-30 15:51 UTC, dbenque commented on internal/kubernetes/drainer.go
> +				}
I think that we show decode that prefix in every case. The data is going to be present all the time thanks to the code in MarkDrain, so we should decode it every time (not only when it fails).
I would move that piece of code just after the capture of LastTransitionTime.

2021-07-30 15:51 UTC, dbenque commented on internal/kubernetes/drainer.go
> +func (d *APICordonDrainer) MarkDrain(n *core.Node, when, finish time.Time, failed bool, failCount int32) error {
Can you please update the unittest to take into account the new prefix?

What do you think about adding a unittest also for the func IsMarkedForDrain? (that maybe we should rename now to GetDrainConditionStatus, WDYT ?)

2021-07-30 15:51 UTC, dbenque commented on internal/kubernetes/eventhandler.go
> +			h.eventRecorder.Event(nr, core.EventTypeWarning, eventReasonDrainFailed, "Pod failed to Drain after multiple retries. Uncordoning node to free slot.")
Let's not speculate on the failure reason (could be eviction API call problem, especially when we use custom eviction endpoint). I would change the message to:
```
Drain still failing after multiple retries. Uncordoning and ignoring the node.
```

2021-07-30 15:51 UTC, dbenque commented on internal/kubernetes/eventhandler.go
> +func (h *DrainingResourceEventHandler) scheduleDrain(n *core.Node, fc int32) {
long name for the second parameters since the int32 does not really express the purpose.

2021-08-05 05:40 UTC, willquan7 commented on internal/kubernetes/drainSchedule.go
> +		when = when.Add(time.Duration(2*failedCount) * time.Hour) // add backoff delay
ok, I'll need to account for large scheduleGroups in the future.

2021-08-05 05:41 UTC, willquan7 commented on internal/kubernetes/drainer.go
>  			msgSuffix = fmt.Sprintf(" | %s: %s", CompletedStr, finish.Format(time.RFC3339))
agree

2021-08-05 05:41 UTC, willquan7 commented on internal/kubernetes/eventhandler.go
> +				logger.Warn("Drain Failed: MaxDrainAttempts reached")
agree

2021-08-05 05:41 UTC, willquan7 commented on internal/kubernetes/drainer.go
> +				}
ok

2021-08-05 05:42 UTC, willquan7 commented on internal/kubernetes/eventhandler.go
> +			h.eventRecorder.Event(nr, core.EventTypeWarning, eventReasonDrainFailed, "Pod failed to Drain after multiple retries. Uncordoning node to free slot.")
ok

2021-08-05 05:42 UTC, willquan7 commented on internal/kubernetes/eventhandler.go
> +func (h *DrainingResourceEventHandler) scheduleDrain(n *core.Node, fc int32) {
agree

2021-08-05 05:42 UTC, willquan7 commented on internal/kubernetes/drainer.go
> +func (d *APICordonDrainer) MarkDrain(n *core.Node, when, finish time.Time, failed bool, failCount int32) error {
yes, adding new UT.

2021-08-05 05:43 UTC, willquan7 commented on internal/kubernetes/drainer.go
> +func (d *APICordonDrainer) MarkDrain(n *core.Node, when, finish time.Time, failed bool, failCount int32) error {
Also did the refactor to rename IsMarkedForDrain -> GetDrainConditionStatus.

2021-08-05 05:45 UTC, willquan7 commented
I have edited description to add section 'Example of a failed drain on a node'. 
This provides an example of what you can expect on a node when drain fails.

2021-08-06 08:52 UTC, dbenque approved these changes

2021-08-06 08:56 UTC, merged