Use draino configuration value of out of scope
DataDog/draino pull request #44
Opened 2021-11-03 16:45 UTC by ryanmcnamara

Hopefully this will make it more clear to users when a node is out of
scope instead of just having the value of the annotation be empty

for https://datadoghq.atlassian.net/browse/COMPUTE-997

2021-11-03 16:48 UTC, ryanmcnamara commented on internal/kubernetes/limiter_test.go
> +			name:          "not limited",
this test flaked for me (I couldn't repro though)
That's why I improved the vars here
Lmk if you want me to revert / do separate

2021-11-03 16:48 UTC, ryanmcnamara commented on internal/kubernetes/observability.go
> +	OutOfScopeAnnotationValue  = "out-of-scope"
happy to change this value to something else if you prefer

2021-11-03 16:48 UTC, ryanmcnamara commented on internal/kubernetes/observability_test.go
> -			wantErr: false,
removed the additional tests since I consolidated the update logic and the update-checking logic into the same func which is tested elsewhere

2021-11-03 16:48 UTC, ryanmcnamara commented
I tested this on biscuits and it worked as I expected

2021-11-03 19:24 UTC, dbenque commented on internal/kubernetes/limiter_test.go
> +			name:          "not limited",
yes I know, it is for me also.
I think it has been instable since it was introduced. Need to be fixed.

2021-11-03 19:33 UTC, dbenque requested changes

2021-11-03 19:33 UTC, dbenque commented on internal/kubernetes/observability.go
> +					InScope:                         len(node.Annotations[ConfigurationAnnotationKey]) > 0 || node.Annotations[ConfigurationAnnotationKey] == OutOfScopeAnnotationValue,
I don't think this is correct, shouldn't it be:
```
len(node.Annotations[ConfigurationAnnotationKey]) > 0 && node.Annotations[ConfigurationAnnotationKey] != OutOfScopeAnnotationValue
```
The value should be true when the node is in scope.

2021-11-03 21:19 UTC, ryanmcnamara commented on internal/kubernetes/observability.go
> +					InScope:                         len(node.Annotations[ConfigurationAnnotationKey]) > 0 || node.Annotations[ConfigurationAnnotationKey] == OutOfScopeAnnotationValue,
whoops, good catch :+1:

2021-11-03 21:20 UTC, ryanmcnamara commented on internal/kubernetes/observability.go
> +					InScope:                         len(node.Annotations[ConfigurationAnnotationKey]) > 0 || node.Annotations[ConfigurationAnnotationKey] == OutOfScopeAnnotationValue,
related: we're always going to need that nonempty check, adding back
otherwise we'll consider not-yet-marked nodes as in scope, seems better to wait for them to be marked

2021-11-04 13:44 UTC, dbenque approved these changes

2021-11-04 14:31 UTC, merged