Short lived pod filter
DataDog/draino pull request #75
Opened 2022-06-08 17:49 UTC by dbenque

There are some pods, like jobs, or gitlabRunner, or sparkRunnner that should not be evicted.
In such case we want to cordon the node but remove this pod from the eviction list. No eviction we wait for them to complete.

We already have an option for cordonOnly, but for gitlabRunner and sparkRunner we cannot use it because these are special cases that do not have controller (ownerReference), and so the classic feature of CordonOnly can't work because it would be overwritten by the force opt-in filter that we would have to use to bypass the check on the controller.

So here the new annotation, explicitly force-opt-in and at the same time avoid the evict activity.

2022-06-08 21:12 UTC, adrienjt requested changes

2022-06-08 21:12 UTC, adrienjt commented on internal/kubernetes/drainer.go
> +	shortLivedPodFilter    PodFilterFunc
Why can this not be part of `filter`?

2022-06-10 16:11 UTC, dbenque commented on internal/kubernetes/drainer.go
> +	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"
not sure way I had to do it manually the `go fmt` and linting by default of my IDE is not doing it...

2022-06-10 16:37 UTC, dbenque commented on internal/kubernetes/drainer.go
> +	shortLivedPodFilter    PodFilterFunc
I thought that excluding in a later phase was more comprehensible.
I now writing the other approach with everything in the filter.

2022-06-10 18:16 UTC, adrienjt approved these changes

2022-06-10 18:17 UTC, merged