first draft of PDB analyser with new controller runtime
DataDog/draino pull request #98
Opened 2022-11-01 10:59 UTC by dhenkel92

2022-11-02 05:43 UTC, adrienjt requested changes
Looks great! Comments are mostly about details. Also, I would like to see this code used already.

2022-11-02 05:43 UTC, adrienjt commented on internal/kubernetes/informer/get_from_index.go
> +	indexInformer, err := i.GetSharedIndexInformer(ctx, obj)
Since obj is only used for its type, would something like this compile?

```suggestion
func GetFromIndex[T clientcr.Object](ctx context.Context, i GetSharedIndexInformer, idx, val string) ([]T, error) {
	var obj T
	indexInformer, err := i.GetSharedIndexInformer(ctx, &obj)
```

Called like this

```go
GetFromIndex[policyv1.PodDisruptionBudget](...)
```

2022-11-02 05:43 UTC, adrienjt commented on internal/kubernetes/utils/array.go
> +func Includes[T comparable](obj T, lst []T) bool {
You're already using IndexFunc, so you may as well use Contains: https://pkg.go.dev/golang.org/x/exp/slices#Contains

2022-11-02 05:43 UTC, adrienjt commented on internal/kubernetes/informer/get_from_index.go
> +func GetFromIndex[T clientcr.Object](ctx context.Context, i GetSharedIndexInformer, idx, val string, obj T) ([]T, error) {
GetFromIndex could be a private method of Informer, because it doesn't need to be mocked. You wouldn't need the GetSharedIndexInformer interface and could simply make GetSharedIndexInformer a private method too.

2022-11-02 05:43 UTC, adrienjt commented on cmd/draino/draino.go
> +	informer, err := informer.New(mgr.GetClient(), mgr.GetCache())
I think that the right term for this object is index, not informer. (It uses informers internally.)

2022-11-02 05:43 UTC, adrienjt commented on internal/kubernetes/analyser/interface.go
> +	BlockingPodsOnNode(ctx context.Context, nodeName string) ([]BlockingPod, error)
Could you use this in internal/kubernetes/drainer.go already to delete rather than evict a pod if it is blocking its PDB? That way we wouldn't merge code that doesn't run, and it would be immediately useful (even without the prioritization of nodes).

2022-11-02 07:27 UTC, dhenkel92 commented on internal/kubernetes/informer/get_from_index.go
> +	indexInformer, err := i.GetSharedIndexInformer(ctx, obj)
I've tried that, but unfortunately the GetSharedIndexInformer will fail with 
```
expected pointer, but got nil
```

2022-11-02 07:27 UTC, dhenkel92 commented on internal/kubernetes/informer/get_from_index.go
> +func GetFromIndex[T clientcr.Object](ctx context.Context, i GetSharedIndexInformer, idx, val string, obj T) ([]T, error) {
Unfortunately, Go doesn't like generic methods 😞

2022-11-02 07:29 UTC, dhenkel92 commented on internal/kubernetes/analyser/pdb_analyser.go
> +		pdbs, err := a.pdbInformer.GetPDBsBlockedByPod(ctx, pod.GetName(), pod.GetNamespace())
Is there a general guideline about this?

2022-11-02 07:39 UTC, dhenkel92 commented on internal/kubernetes/utils/array.go
> +func Includes[T comparable](obj T, lst []T) bool {
Thanks for the hint. Haven't found this function 🙂

2022-11-02 08:03 UTC, dhenkel92 commented on internal/kubernetes/informer/fake.go
> +	}
You got me 😆 
I was too lazy to touch all the line where `createPod` was used again, so I made it "optional". I'll update it.

2022-11-02 08:32 UTC, dhenkel92 commented on internal/kubernetes/analyser/interface.go
> +	BlockingPodsOnNode(ctx context.Context, nodeName string) ([]BlockingPod, error)
I think we could use it, but we have to make sure that using the controller-manager in combination with the old system will work & not increase the memory too much. I'll prepare a separate PR, so that we can test it 🙂

2022-11-03 03:58 UTC, adrienjt commented on internal/kubernetes/index/get_from_index.go
> +func GetFromIndex[T clientcr.Object](ctx context.Context, i GetSharedIndexInformer, idx, val string, obj T) ([]T, error) {
```suggestion
func GetFromIndex[T clientcr.Object](ctx context.Context, i GetSharedIndexInformer, idx, key string, obj T) ([]T, error) {
```

2022-11-03 03:58 UTC, adrienjt commented on internal/kubernetes/informer/get_from_index.go
> +	indexInformer, err := i.GetSharedIndexInformer(ctx, obj)
Oh, right, Pod doesn't implement Object, *Pod does, but we can't use it as T because we need to create a Pod struct.

So we need to use this pattern: https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#pointer-method-example

Simplified application: https://go.dev/play/p/Nlje9NsVLda

2022-11-03 07:27 UTC, dhenkel92 commented on internal/kubernetes/informer/get_from_index.go
> +	indexInformer, err := i.GetSharedIndexInformer(ctx, obj)
https://github.com/DataDog/draino/pull/98/commits/b3a9f802561328f2290105d70c9c8238032414fc

2022-11-03 14:41 UTC, dbenque commented on internal/kubernetes/index/pdb.go
> +	selector, err := metav1.LabelSelectorAsSelector(pdb.Spec.Selector)
can't we pass the selector inside the ListOptions ?

2022-11-03 14:54 UTC, dbenque reviewed
I think we can use the selector in the List function.

2022-11-03 14:54 UTC, dbenque commented on internal/kubernetes/index/pdb.go
> +	selector, err := metav1.LabelSelectorAsSelector(pdb.Spec.Selector)
can't we pass the selector inside the ListOptions ?

2022-11-04 08:32 UTC, dhenkel92 commented on internal/kubernetes/index/pdb.go
> +	selector, err := metav1.LabelSelectorAsSelector(pdb.Spec.Selector)
Great idea, I haven't thought about that at all. Unfortunately, this would not include the `matchExpressionss` of a PDB.

2022-11-04 14:09 UTC, dbenque commented on internal/kubernetes/index/pdb.go
> +	selector, err := metav1.LabelSelectorAsSelector(pdb.Spec.Selector)
agree. Let's keep this.

2022-11-04 14:09 UTC, dbenque approved these changes

2022-11-04 21:28 UTC, adrienjt commented on cmd/draino/draino.go
> +	_ = analyser.NewPDBAnalyser(indexer)
As discussed, I'd rather not merge dead code.

2022-11-07 09:48 UTC, merged

2022-11-07 15:26 UTC, adrienjt commented on cmd/draino/draino.go
> +	_ = analyser.NewPDBAnalyser(indexer)
> we can do that in a dedicated branch, but that will end up with a gigantic PR at the end that will not make any sense, I mean impossible to review

That is not what I meant, see my previous comment: https://github.com/DataDog/draino/pull/98#discussion_r1011215696

I would have liked this to be used in the existing drainer to delete rather than evict unready pods (even if not prioritized). At the very least, I would have liked to see some metrics that could help us identify problematic pods already.